# Generated by Django 5.2.3 on 2025-06-17 21:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('start_year', models.IntegerField(help_text='The year the apprenticeship begins.', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)])),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)])),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OPS', 'Operational'), ('TRAIN', 'Training'), ('VOCAT', 'Vocational School')], max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('hours', models.FloatField()),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='berichtsheft.week')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='berichtsheft.logbook')),
            ],
            options={
                'ordering': ['year_number'],
            },
        ),
        migrations.AddField(
            model_name='week',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='berichtsheft.year'),
        ),
    ]
