# Generated by Django 5.2.3 on 2025-06-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berichtsheft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='logbook',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='logbook',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='logbook',
            name='student_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='logbook',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
